name: Bug Report
description: There's someting wrong with the project itself.
title: "[Project | Bug] Your Title Here"
labels: ["bug"]

body:
    - type: textarea
        id: bug-description
        attributes:
            label: Describe the bug
            description: What happened? Also tell us, what did you expect to happen?
            placeholder: Tell us what you see!
            value: "A bug happened!"
        validations:
            required: true
    - type: textarea
        id: reproduction
        attributes:
            label: Reproduction
            description: How can we reproduce the bug? Please provide the steps to reproduce the bug.
            placeholder: |
                1. 
                2. 
                3.
                ..
        validations:
            required: true
    - type: dropdown
        id: system
        attributes:
            label: System
            description: Which operating system are you using to reproduce the bug?
            multiple: false
            options:
                - Windows 11
                - Windows 10
                - Windows 8/8.1
                - Windows 7
            validations:
              required: true
    - type: textarea
        id: others
        attributes:
            label: Additional Notes (optional)
            description: Is there anything else you'd like to tell us? If you choose `Others` in the browser or system field, please specify here.
        validations:
            required: false
    - type: checkboxes
        id: checkboxes
        attributes:
            label: Validations
            description: Before submitting the issue, please make sure you do the following
            options:
                - label: Check that there isn't [already an issue](https://github.com/iNKORE-NET/UI.WPF.Modern/issues) that reports the same issue to avoid creating a duplicate.
                  required: true
                - label: Check that this is a concrete bug. If you're looking to ask for help or support, open a [GitHub Discussion](https://github.com/iNKORE-NET/UI.WPF.Modern/discussions) or join [our community](https://inkore.net/about#social).
                  required: true
                - label: I know that we can't guarantee that we will satisfy your request. This is not reall our duty to do everything anyone asks for. Also, I will treat our staff, contributors, and other users with respect and kindness.
                  required: true
        validations:
            required: true