name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build and pack
        continue-on-error: true
        run: |
          dotnet build .\source\iNKORE.UI.WPF.Modern
          dotnet build .\source\iNKORE.UI.WPF.Modern.SampleApp
        # dotnet pack .\source\iNKORE.UI.WPF.Modern.Controls --configuration Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg

      - name: Upload binary libraries of iNKORE.UI.WPF.Modern.Controls
        uses: actions/upload-artifact@v3
        with:
          name: iNKORE.UI.WPF.Modern.Controls dlls
          path: .\source\iNKORE.UI.WPF.Modern.Controls\bin\Debug

      - name: Upload sample apps
        uses: actions/upload-artifact@v3
        with:
          name: iNKORE.UI.WPF.Modern.SampleApp files
          path: .\source\iNKORE.UI.WPF.Modern.SampleApp\bin\Debug
